name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint || true

      - name: Build
        env:
          NEXT_PUBLIC_SENTRY_DSN: ''
          NEXT_PUBLIC_ENVIRONMENT: 'ci'
          OPENAI_API_KEY: dummy
          NEXTAUTH_SECRET: dummy
          MONGODB_URI: mongodb://localhost:27017/dummy
        run: npm run build


